### ISSUE TITLE
Usage of semantic versioning and github tags

### ISSUE THREAD

**Issue by diogogomes** [minetest-mods/signs_lib#15] opened 2017-05-20 01:18 UTC
I propose the usage of [semantic versioning](http://semver.org/) and GitHub tags.

The actual master branch of signs_lib is incompatible with stable version of Minetest (0.4.15) and if someone want a compatible version of mod is inconvenient to search in commit history.

I propose GitHub tags, it's more easy to manage with Bower and to download,.

### **Important**
**My suggestion isn't create versions tags like Minetest but create own version tags.**
Example: 1.0.0, etc

**Comment by VanessaE** [comment] 2017-05-20 04:29
I will not be using semantic versioning on my mods, and I do not target stable/release versions when they get this old.  Minetest engine should be in feature-freeze about now, and release is in about two weeks.

**Comment by diogo-gomes** [comment] 2017-05-20 14:24
I understand but until then, your mod can't be installed with mob managers.

I'll fork your mod to create a fallback for these situations.

I hope someday you reconsider and create tags (can be without semantic versioning) to facilitate the installation for newcomers.

**Comment by diogo-gomes** [comment] 2017-05-20 15:17
# Signs Lib (versioned)

**Minetest mod signs_lib (with versions to easy management and better Minetest compatibility)**

---
## Install

### Minetest Bower

**Signs Lib (versioned)** is on **[Minetest Bower](https://minetest-bower.herokuapp.com/mods/signs-lib_versioned)** *(a mod repository and package manager for Minetest)*

You can easily install with the command:

`bower install --save mobs-lib_versioned`

More information [here](https://minetest-bower.herokuapp.com/mods/signs-lib_versioned).


### Manual
You can download the [latest release](https://github.com/diogo-gomes/signs-lib_versioned/releases) and extract it to your `mods` folder.

More information [here](http://wiki.minetest.net/Installing_Mods).

**Comment by kaeza** [comment] 2017-05-20 15:18
I'm OK with using tags to mark the last version working on a given version of the engine, but somebody will have to take the time to build a list.

**Comment by diogo-gomes** [comment] 2017-05-20 15:25
@kaeza , I can do it. It's fast and easy. I just have done in my fork **[Signs Lib (versioned)](https://github.com/diogo-gomes/signs-lib_versionedl)**

**Comment by diogo-gomes** [comment] 2017-05-20 15:48
@kaeza, It seems (I don't understand why) @VanessaE don't want at any cost. You can always use my fallback.

**Comment by VanessaE** [comment] 2017-05-20 16:02
I disagree with it because like all of the other mods I maintain (ok, this one's more @kaeza's than mine), signs_lib is rolling-release, so version numbers make no sense.  Also I closed this before I saw the rest of the thread (github didn't refresh the page for some reason).

**Comment by diogo-gomes** [comment] 2017-05-20 16:35
I understand the rolling release, but if you analyse Linux Distributions that are rolling releases, all of them have some kind of releases points or snapshots or what you want to call it.

**These release tags/points/snapshots can be only to mark big changes like this one in your mods** (I just found homedecor broken but I'll do not open an issue until know your opinion).

**You can always adopt another type of versioning like year and month (Ex:2017.05) or just create a tag when have big changes in code (that crash Minetest stable release).**

_I really don't know if are a lot of people or not using bower like me but after your merges the simple method `bower update` became to the regression of verify all mods manually and or download the specific commit or install with bower the specific commit._

**Comment by VanessaE** [comment] 2018-06-06 11:40
The official repo for this project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/signs_lib/issues

**Closed by VanessaE** 2018-06-06 11:40 UTC
